### ISSUE TITLE
Is it possible to go full gRPC now with the tonic crate?

### ISSUE THREAD

**Issue by liufuyang** [durch/rust-bigtable#4]

**Comment by durch** [comment]
@liufuyang thanks for submitting. Anything is possible, will do some preliminary investigation and get back to you

**Comment by liufuyang** [comment]
Thank you. And if there is some simple task others can help with, please let me know as well :)

**Comment by mvines** [comment]
Yes it is possible!   Check out https://github.com/solana-labs/solana/tree/master/storage-bigtable.  The code in `src/lib.rs` is specific to my project, but the remainder of this crate should be generic and reusable.   Using just the gRPC interface is a little painful at times (such as decoding a `read_rows` response) so I think there's still value in building a Rust-specific API over the protobuf

**Comment by liufuyang** [comment]
I see. Thank you for the info 👍

**Comment by liufuyang** [comment]
@mvines I used quite some of your code and started on an idea here https://github.com/liufuyang/bigtable_rs 
I hope it's okey to borrow some of the code you have in your project? 
@durch I hope it's okay that I am trying of a slightly different approach to try to make a bigtable client, as in the future when I am about to use the client in my backend, the performance will be an important to the application I am working on.
